services:

    napkin-exchange-server:

        container_name: napkin-exchange-server
        
        image: softwareshinobi/napkin-exchange-server

        depends_on:

           - napkin-exchange-database

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8888:8888"

        environment:

            DB_HOST: napkin-exchange-database

            DB_NAME: napkin_exchange_server

            DB_USER: napkin_exchange_server

            DB_PASS: napkin_exchange_server

    napkin-exchange-workflow:

        container_name: napkin-exchange-workflow

        image: nginx
      
      ##  volumes:
        
    ##        - dashboard:/tmp

        restart: unless-stopped          

        ports:

            - 8881:8000

    napkin-exchange-database:

        container_name: napkin-exchange-database

        image: mariadb

        restart: unless-stopped
     ##   volumes:

     ##       - ./.container-volumes/mysql-server:/var/lib/mysql

        ports:

            - "3306:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: napkin_exchange_server

            MYSQL_USER: napkin_exchange_server

            MYSQL_PASSWORD: napkin_exchange_server

    napkin-exchange-phpmyadmin:

        container_name: napkin-exchange-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        restart: unless-stopped

        depends_on:

           - napkin-exchange-database

        links:

           - napkin-exchange-database

        ports:

            - 8830:80

        environment:

            PMA_HOST: napkin-exchange-database

##            PMA_PORT: 3306
##
##            PMA_ARBITRARY: 1
##
