services:

    valorant-digital-headquarters-docs:

        container_name: valorant-digital-headquarters-docs

        image: titom73/mkdocs
      
        volumes:
        
            - ${PWD}:/docs
            
        ports:

            - 8880:8000

    agenteightmysql:

        container_name: agenteightmysql

        image: mysql:8

        volumes:

            - ./.container-volumes/mysql-server:/var/lib/mysql

        ports:

            - "3306:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: agent_eight_central

            MYSQL_USER: agent_eight_central

            MYSQL_PASSWORD: agent_eight_central

        healthcheck:

            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]

            interval: 3s

            timeout: 5s

            retries: 5

    valorant-digital-headquarters-phpmyadmin:

        container_name: valorant-digital-headquarters-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - agenteightmysql

        links:

           - agenteightmysql

        ports:

            - 8830:80

        environment:

            PMA_HOST: agenteightmysql

            PMA_PORT: 3306

            PMA_ARBITRARY: 1
