services:

    links:

        container_name: links

        image: titom73/mkdocs

        volumes:
        
            - ${PWD}:/docs/
            
            - ${PWD}/mkdocs.yml:/docs/mkdocs.yml
         
        ports:

            - 8881:8000
