package digital.softwareshinobi.napkinexchange.notification.type;

public enum NotificationType {

    BUY_STOP_TRIGGER,
    /////
    SYSTEM_NOTIFICATION,
    /////
    NEW_TRADER_CREATED,
    /////
    LONG_MARKET_BUY_CREATED,
    /////
    LONG_SMART_BUY_CREATED,
    LONG_SMART_BUY_FULFILLED,
    LONG_SMART_BUY_CANCELLATION,
    /////
    MARKET_BUY_ORDER_CREATED,
    MARKET_BUY_ORDER_FULFILLED,
    /////
    NEW_LIMIT_ORDER_CREATED,
    /////
    LONG_STOP_LOSS_CREATED,
    LONG_STOP_LOSS_TRIGGERED,
    /////
    LONG_TAKE_PROFIT_CREATED,
    LONG_TAKE_PROFIT_TRIGGERED,
    /////
    MARKET_SELL_ORDER_CREATED,
    MARKET_SELL_ORDER_FULFILLED,
    /////
    TRADER_INSUFFICIENT_FUNDS,
    TRADER_INSUFFICIENT_SECURITY_HOLDINGS,

}

/*

    ////
    //  LONG_SELL_ORDER_CREATED,
    //  LONG_SELL_ORDER_FULFILLED,
    ////////





*/
