version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 8080:32400
    volumes:
      - ./path/to/library:/config
      - ./path/to/tvseries:/tv
      - ./path/to/movies:/movies
    restart: unless-stopped
