services:

    website:

        container_name: website

        image: website

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 4446:80

#    links:
#
#       container_name: links
#
#        image: softwareshinobi/valorant-digital-workspace-links
#
#        ports:
#
#            - 4444:80
#
