
docs_dir: docs

site_name: Docs / Valorant Digital Scrum

theme:

    palette:
        
        scheme: slate

        primary: deep orange

        accent: purple
        
    ##
    ## Find More Themes Here:
    ##
    ##     https://mkdocs.github.io/mkdocs-bootswatch/
    ##
    ## List of theme values:
    ##
    ##     mkdocs, readthedocs, material, cerulean, cosmo, 
    ##     cyborg, darkly, flatly, journal, litera, lumen, lux,
    ##     materia, minty, pulse, sandstone, simplex, slate, solar,
    ##     spacelab, superhero, united, yeti 
    ##
        
    name: material
    
    ## 
    ## you can alternate colors for the navigation header.
    ##
    ## Allowed values: primary (the default), dark, and light:
    ##
    
    nav_style: primary

extra_css: [styling.css]
